-- MySQL Script generated by MySQL Workbench
-- Sat Jan 12 22:14:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taskmanager_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taskmanager_db
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `taskmanager_db` DEFAULT CHARACTER SET utf8 ;
-- USE `taskmanager_db` ;

-- -----------------------------------------------------
-- Table `taskmanager_db`.`users`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `taskmanager_db`.`users` ;


CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskmanager_db`.`task_status`
-- -----------------------------------------------------
--  DROP TABLE IF EXISTS `taskmanager_db`.`task_status` ;

CREATE TABLE IF NOT EXISTS `task_status` (
  `status` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskmanager_db`.`tasks`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `taskmanager_db`.`tasks` ;

CREATE TABLE IF NOT EXISTS `tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `task_status` VARCHAR(50) NOT NULL,
  `users_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `task_UNIQUE` (`task` ASC),
  INDEX `fk_tasks_task_status1_idx` (`task_status` ASC),
  INDEX `fk_tasks_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_tasks_task_status1`
    FOREIGN KEY (`task_status`)
    REFERENCES `task_status` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
